//This program is set up to generate two random pokemon to fight!!!!!

import java.util.Random;

public class WildPokemon {
    private Random rand = new Random();
    private List<Pokemon> pokemonlist;

    public WildPokemon()
    {
        pokemonlist = new Arraylist();
        Pokemon chikorita = new Pokemon("Chikorita");
        pokemonList.add(chikorita);
        Pokemon cyndaquil = new Pokemon("Cyndaquil");
        pokemonList.add(cyndaquil);
        Pokemon totodile = new Pokemon("Totodile");
        pokemonList.add(totodile);

        Pokemon pidgey = new Pokemon("Pidgey");
        pokemonList.add(pidgey);
        Pokemon spearow = new Pokemon("Spearow");
        pokemonList.add(spearow);

        Pokemon hoothoot = new Pokemon("Hoothoot");
        pokemonList.add(hoothoot);
        Pokemon rattata = new Pokemon("rattata");
        pokemonList.add(rattata);
        Pokemon sentret = new Pokemon("sentret");
        pokemonList.add(sentret);
        Pokemon pichu = new Pokemon("pichu");
        pokemonList.add(pichu);
        Pokemon caterpie = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon weedle = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon ledyba = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon spinarak = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon geodude = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon zubat = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon cleffa = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon igglybuff = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon togepi = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon sandshrew = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon ekans= new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon dunsparce = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon mareep = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon wooper = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon gastly = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon unown = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon onyx = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon bellsprout = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon paras = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon hoppip = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon poliwag = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon politoed = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon magikarp = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon goldeen = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon slowpoke = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon oddish = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon bellossom = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon drowzee = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon abra = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon ditto = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon pineco = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon nidoran = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon yanma = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon sunkern = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon exeggcute = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon sudowoodo = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon wobbuffet = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon venonat = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon scyther = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon pinsir = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon koffing = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon grimer = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon magnemite = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon voltorb = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon aipom = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon snubull = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon vulpix = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon growlithe = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon stantler = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon marill = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon diglett = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon mankey = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon meowth = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon psyduck = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon machop = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon tyrogue = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon girafarig = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon tauros= new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon miltank = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon magby = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon smoochum = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon elekid = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon mrmime = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon smeargle = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon natu = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon qwilfish = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon tentacool = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon krabby = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon shuckle = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon staryu = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon shellder = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon corsola = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon octillery = new Pokemon("Totodile");
        Pokemon chinchou = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon seel = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon lickitung = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon tangela = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon eevee= new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon horsea = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon gilgar = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon delibird = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon swinub = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon teddiursa = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon phanpy = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon mantine = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon doduo = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon ponyta = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon cubone = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon phyhorn = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon murkrow = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon houndour = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon slugma = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon sneasel = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon porygon = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon chansey = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon lapras = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon omanyte = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon kabuto = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon aerodactyl = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon snorlax = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon bulbasaur = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon charmander = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon squirtle = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon articuno = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon zapdos = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon moltres= new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon raikou = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon entei = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon suicune = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon dratini = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon larvitar = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon lugia= new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon hooh = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon mew = new Pokemon("Totodile");
        pokemonList.add(rattata);
        Pokemon celebi = new Pokemon("Totodile");
        pokemonList.add(rattata);
    }

    private Pokemon getRandomPokemon(){
        int x = rand.nextInt(pokemonlist.size());
        return pokemonlist.get(x);
    }
}
